APP_SERVER: ''
CODECLIMATE_REPO_TOKEN: ''
COUNTRY_CODE: ''
DB_HOST: ''
DB_NAME: ''
DB_PASSWORD: ''
DB_USERNAME: ''
DEPLOY_USER: ''
EMAIL_ADDRESS: ''
EMAIL_AUTHENTICATION: ''
EMAIL_DOMAIN: ''
EMAIL_PASSWORD: ''
EMAIL_PORT: ''
EMAIL_USERNAME: ''
FILEPICKER_API_KEY: ''
GEONAMES_USERNAME: ''
HOCHO_SALT: ''
LOCALEAPP_KEY: ''
S3_KEY: ''
S3_SECRET: ''
S3_BUCKET: ''
S3_REGION: ''
SSH_PORT: ''
TWITTER_ACCESS_SECRET: ''
TWITTER_ACCESS_TOKEN: ''
TWITTER_KEY: ''
TWITTER_SECRET: ''
discourse_enabled: false
discourse_endpoint: ''
discourse_api_key: ''
discourse_api_username: ''
discourse_lab_category: ''
url: 'http://www.fablabs.dev'
