development: &defaults
  adapter      : postgresql
  encoding     : unicode
  database     : fablabs_develop
  pool         : 20
  min_messages : WARNING

  username : <%= ENV['DEV_DB_USERNAME'] || "postgres" %>
  password : <%= ENV['DEV_DB_PASSWORD'] %>
  host     : <%= ENV['DEV_DB_HOST'] || "127.0.0.1" %>

test:
  <<: *defaults
  database     : fablabs_testdb

production:
  <<: *defaults
  database : <%= ENV['DB_NAME'] %>
  username : <%= ENV['DB_USERNAME'] %>
  password : <%= ENV['DB_PASSWORD'] %>
  host     : <%= ENV['DB_HOST'] %>
