development: &defaults
  adapter      : postgresql
  encoding     : unicode
  database     : fablabs_development
  pool         : 5
  host         : 127.0.0.1
  username     : john
  min_messages : WARNING

test:
  <<: *defaults
  database     : fablabs_test

production:
  <<: *defaults
  database : <%= ENV['DB_NAME'] %>
  username : <%= ENV['DB_USERNAME'] %>
  password : <%= ENV['DB_PASSWORD'] %>
  host     : <%= ENV['DB_HOST'] %>
  host     : <%= ENV['DB_HOST'] %>
